- name: "Run all role tasks for Linux"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    system_adwaita_icons_dir: "{{ adwaita_linux_system_icons_dir }}"
  when: ansible_system == "Linux"

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    system_adwaita_icons_dir: "{{ adwaita_freebsd_system_icons_dir }}"
  when: ansible_os_family == "FreeBSD"

