- name: "Create Adwaita user default icons dirs"
  ansible.builtin.file:
    path: "{{ user_icons_dir }}"
    state: directory
  become: true
  become_user: "{{ adwaita_user_name }}"
  loop:
    - "{{ adwaita_user_default_icons_dir }}"
    - "{{ adwaita_user_default_local_icons_dir }}"
  loop_control:
    loop_var: user_icons_dir

